// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var _requireCount;
    _requireCount = 8;
    $("#require-count").html(_requireCount);
    $("input").blur(function() {
      if ($(this).val() === "") {
        $(this).next(".error").slideDown();
        $(this).parents("tr").find("th").css("background-color", "#f1c40f");
        return $(this).parents("tr").find(".ok").fadeOut();
      }
    });
    return $("input").change(function() {
      var char;
      char = $(this).val().length;
      if (char < 0) {
        return $(this).next(".error").slideDown();
      } else {
        $(this).next(".error").slideUp();
        $(this).parents("tr").find("th").css("background-color", "#f2f2f2");
        $(this).parents("tr").find(".ok").fadeIn();
        _requireCount = _requireCount - 1;
        return $("#require-count").html(_requireCount);
      }
    });
  });

}).call(this);
